{{- range $key, $ingress := .Values.ingresses }}
{{- if $ingress.enabled }}
---
{{- $fullName := printf "%s-%s" (include "app.fullname" $) ($key | replace "_" "-") -}}
{{- if and $ingress.className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className }}
  {{- end }}
{{- end }}
{{- $prefixedTarget := not $ingress.targetAbsolute -}}
{{- $target := and $ingress.target $prefixedTarget | ternary (printf "%s-%s" (include "app.fullname" $) $ingress.target) ($ingress.target | default $fullName) -}}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            {{- if and $ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $target | default $fullName }}
                port:
                  number: {{ $ingress.targetPort | default "8000" }}
              {{- else }}
              serviceName: {{ $target | default $fullName }}
              servicePort: {{ $ingress.targetPort | default "8000" }}
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}
