{{- if .Values.monitoring.alerts }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "app.fullname" . }}-alerts
  labels:
    release: prometheus
    role: alert-rules
    {{- include "app.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "app.fullname" . }}
      rules:
        {{- with .Values.monitoring.alerts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
