{{- range $key, $val := .Values.services }}
---
{{- with $val }}
{{- $name := .fullnameOverride | default (printf "%s-%s" (include "app.fullname" $) ($key | replace "_" "-")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    {{- if .ports }}
    {{- range $portName, $portData := .ports }}
    - name: {{ $portName }}
      port: {{ $portData.port | default "8000" }}
      {{- if and (or (eq .type "NodePort") (eq .type "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      targetPort: {{ $portData.containerPort | default "8000" }}
      protocol: TCP
      {{- if semverCompare ">=1.20-0" $.Capabilities.KubeVersion.GitVersion }}
      appProtocol: http
      {{- end }}
    {{- end }}
    {{- else }}
    - name: http
      port: {{ .port | default "8000" }}
      {{- if and (or (eq .type "NodePort") (eq .type "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      targetPort: {{ .containerPort | default "8000" }}
      protocol: TCP
      {{- if semverCompare ">=1.20-0" $.Capabilities.KubeVersion.GitVersion }}
      appProtocol: http
      {{- end }}
    {{- end }}
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
