{{- range $key, $val := .Values.services }}
---
{{- with $val }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" $ }}-{{ $key | replace "_" "-" }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .port }}
      {{- if and (or (eq .type "NodePort") (eq .type "LoadBalancer")) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      {{- if semverCompare ">=1.20-0" $.Capabilities.KubeVersion.GitVersion }}
      appProtocol: http
      {{- end }}
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
