{{- range $name, $redirect := .Values.redirects }}
{{- $ingress := $redirect.ingress | default dict }}
{{- $className := $ingress.className | default "nginx" }}
{{- if (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion))}}
  {{- if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ingress.annotations "kubernetes.io/ingress.class" $className }}
  {{- end }}
{{- end }}
{{- $nameData := dict "globals" $ "name" $name }}
---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "app.ingressFullname" $nameData }}
  labels:
    {{- include "app.labels" $nameData | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: {{ $redirect.target | quote }}
    {{- with $ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $className }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $source := $redirect.sources }}
    - host: {{ $source | quote }}
    {{- end }}
{{- end }}
