apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
