apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  {{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- if .Values.secretsVolume.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-vol
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  {{- with .Values.secretsVolume.data }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
