{{- if and .Values.hooksSecret .Values.hooks }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-hook
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
stringData:
  {{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- if .Values.secretsVolume.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-vol-hook
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
stringData:
  {{- with .Values.secretsVolume.data }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
